add({ n = 'CECILIA', d = { "I'm sorry.", "I'm just in a big hurry to get to class on time...", "I didn't mean to run into you!" } })
add({ n = '', lg = lg.ruby_cry, d = { "The girl looked up to me, tears streaming down her face. " } })
add({ n = 'GIRL', d = { "...I...I-I know... It's my fault... I-I should've", "been watching where I was going..."} })
add({ n = 'CECILIA', d = {"No... It's both our fault. Here, let me help you."} })
add({ n = '', sm = sm.ruby_worry, d = {"You knelt down and start to pick up the shards.", "The girl looked watched you for a few moments before wiping", "her eyes off and going back to picking up shards."} })
add({ bg = '', lg = '', d = {" ..."} })
add({ d = {" ........"} })
add({ d = {".........................."} }) 
add({ bg = bg.sidewalk_with_campus, lg = lg.ruby_worry, d = {"You finished picking up the shards, but with the time it took,", "You are defintely late."} })
add({ n = 'GIRL', d = {"...Th-thank..."} })
add({ n = '', d = {"Before she could finish her sentence, another girl from far", "away yelled out to the girl."} })
add({ d = {"As the other girl approached her, you decided to run ahead to attend class,", "hoping the teacher will go easy on you since it's a freshman class."}, node = 'nodes/week1/day1/ruby_finish.lua' })

